'use strict';
const {esc}=require('./http');
const FL_BG=`<div class="floating-lines-container" data-floatinglines data-floatinglines-options='{"bendRadius":5,"bendStrength":-0.5,"parallax":true,"speed":0.35,"layerAlpha":1,"lineCount":[10,15,20],"lineDistance":[8,6,4],"lineColor":"#FF1A1A"}' aria-hidden="true"></div>`;
const ORB_BG=`<div class="orb-bg" data-orb aria-hidden="true"></div>`;
const LANYARD=`<div class="lanyard-scene" data-lanyard aria-hidden="true"><div class="lanyard-band"></div><div class="lanyard-clip"></div><div class="lanyard-card"><img src="/static/lanyard-logo.png" alt=""></div></div>`;
function authShell(title,inner,msg){return FL_BG+`<section class="wrap" style="max-width:640px"><p class="kicker">SECURE ACCESS</p><h1 class="h2">${title}</h1>${msg?`<div class="alert err" role="alert">${msg}</div>`:''}${inner}<p class="mono dim" style="text-align:center;font-size:12px">AUTHORIZED ACCESS ONLY &middot; RATE-LIMITED &middot; SECURE SESSION</p></section>`;}
function loginShell(title,inner,msg){return `<div class="lightning-login-wrap">${ORB_BG}${LANYARD}<section class="lightning-login-content"><a class="login-brand-button" href="/" aria-label="Go to HackSpire home"><span class="brand-name">HACK<span>SPIRE</span></span></a><p class="kicker">SECURE ACCESS</p><h1 class="h2">${title}</h1>${msg?`<div class="alert err" role="alert">${msg}</div>`:''}${inner}<p class="mono dim">AUTHORIZED ACCESS ONLY &middot; RATE-LIMITED &middot; SECURE SESSION</p></section></div>`;}
function csrfField(t){return `<input type="hidden" name="csrf" value="${esc(t)}">`;}
function loginForm(csrf,msg){return loginShell('LOGIN',`<form class="form" method="post" action="/login"><label for="email">EMAIL</label><input id="email" name="email" type="email" required autocomplete="email">${csrfField(csrf)}<label for="pw">PASSWORD</label><input id="pw" name="password" type="password" required autocomplete="current-password"><p style="margin-top:18px"><button class="btn btn-primary specular-button" data-specular type="submit" style="width:100%">LOGIN</button></p><p class="dim" style="font-size:14px;text-align:center">No account? <a href="/register">Register</a> &middot; <a href="/forgot-password">Forgot password?</a></p></form>`,msg);}
function regForm(csrf,msg,full){return authShell('JOIN HACKSPIRE',`${full?'<div class="alert err" role="alert">HACKSPIRE MEMBERSHIP IS CURRENTLY FULL.</div>':''}<form class="form" method="post" action="/register" ${full?'aria-disabled="true"':''}><label for="rn">NAME</label><input id="rn" name="name" required maxlength="80" ${full?'disabled':''}><label for="re">EMAIL</label><input id="re" name="email" type="email" required ${full?'disabled':''}>${csrfField(csrf)}<label for="rp">PASSWORD (MIN 8 CHARS)</label><input id="rp" name="password" type="password" required minlength="8" ${full?'disabled':''}><label for="rc">CONFIRM PASSWORD</label><input id="rc" name="confirm" type="password" required ${full?'disabled':''}><label for="ri">SHORT INTRO (OPTIONAL)</label><textarea id="ri" name="bio" rows="3" maxlength="600" ${full?'disabled':''}></textarea><label for="rint">INTERESTS (OPTIONAL)</label><input id="rint" name="interests" maxlength="200" ${full?'disabled':''}><p style="margin-top:18px"><button class="btn btn-primary" type="submit" style="width:100%" ${full?'disabled':''}>${full?'REGISTRATION CLOSED':'REQUEST ACCESS'}</button></p></form>`,msg);}
module.exports={loginForm,regForm,authShell,csrfField};
