'use strict';
const {esc}=require('./http');
const SITE='HackSpire — Cybersecurity Community | Learn. Build. Hack. Grow.';
const DESC='HackSpire is a cybersecurity community where hackers, learners, researchers and builders learn together, build projects, solve CTFs and grow as a team.';
const WT_OPTS=JSON.stringify({color1:'#FF1A1A',color2:'#FF3030',color3:'#FFFFFF',speed:0.2,threadCount:6,frequency:5.0,spread:0.18,taper:1.0,position:0.5,fanMode:'center',glow:0.02,falloff:0.6,thickness:1.1,brightness:0.6,opacity:1.0,mirror:true,shimmer:false,grain:true,grainIntensity:0.05,mouseInteraction:true,mouseStrength:0.3}).replace(/"/g,'&quot;');
const LANYARD=`<div class="lanyard-scene" data-lanyard aria-hidden="true"><div class="lanyard-band"></div><div class="lanyard-clip"></div><div class="lanyard-card"><img src="/static/lanyard-logo.png" alt=""></div></div>`;
function head(title,desc){return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title||SITE)}</title><meta name="description" content="${esc(desc||DESC)}"><meta name="keywords" content="HackSpire,cybersecurity community,cybersecurity,penetration testing,ethical hacking,CTF,Active Directory,digital forensics,DFIR,web security,security research"><link rel="canonical" href="/"><meta property="og:title" content="HackSpire — Learn. Build. Hack. Grow."><meta property="og:description" content="${esc(desc||DESC)}"><meta property="og:type" content="website"><meta name="twitter:card" content="summary"><link rel="icon" type="image/png" href="/static/hackspire-logo.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&family=JetBrains+Mono:wght@400;600;700&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/static/css/main.css"><link rel="stylesheet" href="/static/css/stroketext.css"><link rel="stylesheet" href="/static/css/webthreads.css"><link rel="stylesheet" href="/static/css/lightning.css"><link rel="stylesheet" href="/static/css/orb.css"><link rel="stylesheet" href="/static/css/lanyard.css?v=4"><script src="/static/js/main.js" defer></script><script src="/static/js/stroketext.js" defer></script><script src="/static/js/webthreads.js" defer></script><script src="/static/js/lightning.js" defer></script><script src="/static/js/orb.js" defer></script><script src="/static/js/specular.js" defer></script><script src="/static/js/lanyard.js?v=4" defer></script></head>`;}
function nav(user,active){const a=p=>p===active?' aria-current="page" class="active"':'';const admin=user&&user.role==='ADMIN'?'<a href="/admin/dashboard" class="nav-admin">ADMIN</a>':'';const auth=user?`<a href="/dashboard">DASHBOARD</a>${admin}<a href="/logout" class="btn btn-sm btn-ghost">LOGOUT</a>`:`<a href="/login"${a('/login')}>LOGIN</a><a href="/register" class="btn btn-sm btn-primary">JOIN HACKSPIRE</a>`;return `<a class="skip" href="#main">Skip to content</a><header class="nav" id="topnav"><div class="nav-inner"><nav class="nav-links" aria-label="Primary"><a href="/"${a('/')}>HOME</a><a href="/about"${a('/about')}>ABOUT</a><a href="/learning"${a('/learning')}>LEARNING</a><a href="/team"${a('/team')}>TEAMS</a><a href="/events"${a('/events')}>EVENTS</a><a href="/community"${a('/community')}>COMMUNITY</a><a href="/founder/akash"${a('/founder/akash')}>FOUNDER</a>${auth}</nav><button class="burger" id="burger" aria-label="Open menu" aria-expanded="false" aria-controls="drawer"><span></span><span></span><span></span></button></div></header><div class="drawer" id="drawer" hidden><nav aria-label="Mobile"><a href="/">HOME</a><a href="/about">ABOUT</a><a href="/learning">LEARNING</a><a href="/team">TEAMS</a><a href="/events">EVENTS</a><a href="/community">COMMUNITY</a><a href="/founder/akash">FOUNDER</a>${user?'<a href="/dashboard">DASHBOARD</a><a href="/resources">RESOURCES</a><a href="/labs">LABS</a><a href="/ctf">CTF</a><a href="/profile">PROFILE</a>'+(user.role==='ADMIN'?'<a href="/admin/dashboard">ADMIN</a>':'')+'<a href="/logout">LOGOUT</a>':'<a href="/login">LOGIN</a><a href="/register" class="btn btn-primary">JOIN HACKSPIRE</a>'}</nav></div>`;}
function footer(){return `<footer class="footer"><div class="wrap foot-grid"><div><div class="brand-text">HACK<span>SPIRE</span></div><p class="tagline">LEARN. BUILD. HACK. GROW.</p><p class="mono dim">Hack responsibly. Test only systems you are authorized to test.</p></div><nav aria-label="Footer"><a href="/">Home</a><a href="/about">About</a><a href="/learning">Learning</a><a href="/team">Teams</a><a href="/events">Events</a><a href="/community">Community</a><a href="/founder/akash">Founder</a></nav><div><p class="mono dim">OFFICIAL LINKS</p><a href="https://www.linkedin.com/in/akash2201/" target="_blank" rel="noopener">Akash — LinkedIn ↗</a><a href="https://public-eight-sigma-25.vercel.app/" target="_blank" rel="noopener">Akash — Portfolio ↗</a><a href="https://www.linkedin.com/in/aj49/" target="_blank" rel="noopener">Aslam — LinkedIn ↗</a><p class="mono dim">More channels — COMING SOON</p></div></div><div class="wrap foot-base"><span>© 2026 HackSpire. Built by the community.</span><span class="mono"><i class="dot"></i> SYSTEM ONLINE · AUTHORIZED ACCESS ONLY</span></div></footer>`;}
function page(title,user,active,body,desc){return head(title,desc)+`<body><div class="bg" aria-hidden="true"><div class="grid"></div><div class="glow"></div><div class="scan"></div><div class="web-threads-bg" data-webthreads data-wt-options="${WT_OPTS}"></div></div>`+nav(user,active)+(active==='/'?LANYARD:'')+`<main id="main">${body}</main>`+footer()+`</body></html>`;}
function errPage(code,title,msg){return head(code+' — '+title)+`<body><div class="bg" aria-hidden="true"><div class="grid"></div><div class="web-threads-bg" data-webthreads data-wt-options="${WT_OPTS}"></div></div><main class="wrap err"><p class="mono kicker">ERROR ${code}</p><h1>${esc(title)}</h1><p>${esc(msg)}</p><p><a class="btn btn-primary" href="/">BACK TO HACKSPIRE</a> <a class="btn btn-ghost" href="/login">LOGIN</a></p></main></body></html>`;}
function authPage(title,body,desc){return head(title,desc)+`<body class="auth-page">`+nav(null,'')+`<main id="main">${body}</main>`+footer()+`</body></html>`;}
module.exports={page,authPage,errPage,esc};
