'use strict';
function avatarStroke(word,id,fill){
  const st=[],fl=[];
  for(let i=0;i<word.length;i++){
    st.push(`<tspan style="stroke-dasharray:900;stroke-dashoffset:0;animation:hs-stroke 1.6s ${(i*0.05).toFixed(2)}s both">${word[i]}</tspan>`);
    fl.push(`<tspan fill="${fill}">${word[i]}</tspan>`);
  }
  return `<span class="stroke-text"><svg class="stroke-text__svg" viewBox="-220 -58 440 220" preserveAspectRatio="xMidYMid meet" aria-hidden="true">
  <defs><clipPath id="${id}"><rect x="-220" y="-58" width="440" height="220" style="animation:hs-wipe .9s 1.2s both"/></clipPath></defs>
  <text x="0" y="52" text-anchor="middle" fill="none" stroke="#FF3030" stroke-width="3" stroke-linejoin="round" stroke-linecap="round" style="font-family:var(--sans);font-weight:800;font-size:128px;letter-spacing:-4px">${st.join('')}</text>
  <text x="0" y="52" text-anchor="middle" stroke="none" style="font-family:var(--sans);font-weight:800;font-size:128px;letter-spacing:-4px" clip-path="url(#${id})">${fl.join('')}</text>
  </svg></span>`;}
function founderPage(){return `<section class="wrap"><p class="kicker">HACKSPIRE ADMIN</p><div class="founder-hero"><img class="founder-photo" style="display:block;width:200px;height:250px;max-width:100%;aspect-ratio:4/5;object-fit:cover;object-position:center 28%" src="/static/akash-founder.jpg" alt="Akash, HackSpire founder"><div><span class="pill on">FOUNDER &amp; ADMIN</span><h1 class="h2">AKASH</h1><p class="mono" style="color:#FF6666;letter-spacing:2px">FOUNDER &amp; ADMIN &middot; COMMUNITY ADMIN &middot; SYSTEM ONLINE</p><p class="mono dim" style="font-size:12px">CYBERSECURITY &middot; PENETRATION TESTING &middot; ACTIVE DIRECTORY &middot; CTF</p><p style="font-size:20px;max-width:640px">Don&apos;t learn cybersecurity alone. Build your team. Share your knowledge. Grow together.</p></div></div><div class="cards c2" style="margin-top:26px"><div class="card"><h3>PROFILE</h3><table><tr><th>NAME</th><td>Akash</td></tr><tr><th>ROLE</th><td>Founder &amp; Admin</td></tr><tr><th>COMMUNITY</th><td>HackSpire</td></tr><tr><th>FOCUS</th><td>Cybersecurity, Penetration Testing, Active Directory, CTF, Security Research, Community Building</td></tr></table></div><div class="card"><h3>LEADERSHIP STATEMENT</h3><p>I&apos;m a cybersecurity enthusiast and Junior Penetration Tester passionate about understanding how systems behave under pressure—and how to make them stronger.</p><p>My journey is built around hands-on learning: exploring Active Directory security, network enumeration, penetration testing, defensive IoT experiments, and CTF challenges.</p><p>As the founder of HackSpire, I believe cybersecurity is better learned together. My goal is to build a community where people can share knowledge, form strong teams, build real projects, solve challenges, and grow together.</p><p>I bring a builder&apos;s mindset to security: test responsibly, learn continuously, document clearly, and leave every authorized environment stronger than I found it.</p></div></div><div class="card" style="margin-top:16px"><h3>FOUNDER QUOTE</h3><p style="font-size:20px;color:#fff">Don&apos;t learn alone. Build your team. Share your knowledge. Grow together.</p><div class="cta-row" style="justify-content:flex-start"><a class="btn btn-primary btn-sm" href="https://public-eight-sigma-25.vercel.app/" target="_blank" rel="noopener">PORTFOLIO</a><a class="btn btn-ghost btn-sm" href="https://www.linkedin.com/in/akash2201/" target="_blank" rel="noopener">LINKEDIN</a></div></div></section>`;}
function aslamPage(){return `<section class="wrap"><p class="kicker">PROFILE HEADER</p><div class="founder-hero"><img class="profile-photo" src="/static/aslam-javeed.jpg" alt="Aslam Javeed"><div><span class="pill">TEAM MEMBER</span><h1 class="h2">ASLAM JAVEED</h1><p class="mono" style="color:#FF6666;letter-spacing:2px">TEAM MEMBER &middot; Cybersecurity | DFIR | Digital Investigation</p><p class="mono dim" style="font-size:12px">DFIR &middot; DIGITAL FORENSICS &middot; INCIDENT RESPONSE</p></div></div><div class="cards c2" style="margin-top:22px"><div class="card"><h3>ABOUT</h3><p>Driven by curiosity. Focused on evidence. Built for the investigation.</p><p>A Cybersecurity Engineering student passionate about Digital Forensics, Incident Response, and cyber investigation. I enjoy uncovering digital evidence, analysing threats, and understanding the story behind an incident.</p><p>At HackSpire, I bring an investigative mindset to the team—helping uncover what happened, analyse evidence, and turn incidents into lessons that make systems more resilient.</p></div><div class="card"><h3>EXPERTISE &amp; FOCUS</h3><ul style="color:#A3A3A3"><li>Digital Forensics</li><li>Incident Response</li><li>Cyber Investigation</li><li>Threat Analysis</li><li>Evidence Analysis</li></ul><h3 style="margin-top:14px">SOCIAL LINKS</h3><p><a class="btn btn-ghost btn-sm" href="https://www.linkedin.com/in/aj49/" target="_blank" rel="noopener">LINKEDIN</a><a class="btn btn-primary btn-sm" href="https://aslamxsthets.github.io/Portfolio-Gear5/" target="_blank" rel="noopener">PORTFOLIO ↗</a></p></div></div><p style="margin-top:18px"><a class="btn btn-ghost btn-sm" href="/team">BACK TO HACKSPIRE TEAM</a></p></section>`;}
module.exports={founderPage,aslamPage};
